version: '3'

services:
  hive-metastore:
    image: ghcr.io/clinia/hive:3.1.3-postgresql-metastore
    env_file:
      - hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      - SERVICE_PRECONDITION="hive-metastore-postgresql:5432"
    depends_on:
      - postgres
  
  hive-metastore-postgresql:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
    
