name: Hive Release

on:
  workflow_dispatch:
    inputs:
      hive_version:
        description: 'Hive version to build the image on'
        required: true
        default: '3.1.3'

jobs:
  'hive':
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=ghcr.io/clinia/hive
          HIVE_VERSION=${{ github.event.inputs.hive_version }}
          TAGS="${DOCKER_IMAGE}:${HIVE_VERSION}-postgresql-metastore"

          echo ::set-output name=tags::${TAGS}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ghcr_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: ${{ steps.prep.outputs.tags }}